-- Plugin highlights.
--
-- Where possible, groups link to the semantic helper groups from editor.lua
-- (ErrorSign, WhiteOnRed, FloatWindow, Diff*, …) so plugin styling stays
-- consistent with the legacy envy.vim. Organised by plugin.

local M = {}

function M.get(c, opts, variant)
  return {
    -- gitsigns.nvim
    GitSignsAdd          = { fg = c.green },
    GitSignsChange       = { fg = c.orange },
    GitSignsDelete       = { fg = c.red },
    GitSignsChangedelete = { fg = c.orange },
    GitSignsTopdelete    = { fg = c.red },
    GitSignsUntracked    = { fg = c.grey },
    GitSignsAddNr        = { fg = c.green },
    GitSignsChangeNr     = { fg = c.orange },
    GitSignsDeleteNr     = { fg = c.red },
    GitSignsAddLn        = { link = "DiffAdd" },
    GitSignsChangeLn     = { link = "DiffChange" },
    GitSignsDeleteLn     = { link = "DiffDelete" },
    GitSignsCurrentLineBlame = { link = "Comment" },
    GitSignsStagedAdd    = { fg = c.green },
    GitSignsStagedChange = { fg = c.orange },
    GitSignsStagedDelete = { fg = c.red },

    -- Telescope
    TelescopeNormal        = { fg = c.fg, bg = c.white },
    TelescopeBorder        = { link = "Comment" },
    TelescopePromptBorder  = { link = "Comment" },
    TelescopeResultsBorder = { link = "Comment" },
    TelescopePreviewBorder = { link = "Comment" },
    TelescopePromptNormal  = { fg = c.fg, bg = c.white },
    TelescopePromptPrefix  = { fg = c.red },
    TelescopePromptCounter = { link = "Comment" },
    TelescopeSelection     = { bg = c.lgrey1, bold = true },
    TelescopeSelectionCaret= { fg = c.red, bg = c.lgrey1 },
    TelescopeMultiSelection= { fg = c.purple },
    TelescopeMatching      = { fg = c.blue, bold = true },
    TelescopeTitle         = { fg = c.fg, bold = true },
    TelescopePromptTitle   = { fg = c.fg, bold = true },
    TelescopeResultsTitle  = { fg = c.fg, bold = true },
    TelescopePreviewTitle  = { fg = c.fg, bold = true },

    -- nvim-cmp
    CmpItemAbbr           = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.grey, strikethrough = true },
    CmpItemAbbrMatch      = { fg = c.blue, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.blue, bold = true },
    CmpItemMenu           = { link = "Comment" },
    CmpItemKind           = { fg = c.fg },
    CmpItemKindFunction   = { link = "Function" },
    CmpItemKindMethod     = { link = "Function" },
    CmpItemKindVariable   = { link = "Identifier" },
    CmpItemKindKeyword    = { link = "Keyword" },
    CmpItemKindClass      = { link = "Type" },
    CmpItemKindStruct     = { link = "Type" },
    CmpItemKindInterface  = { link = "Type" },
    CmpItemKindEnum       = { link = "Type" },
    CmpItemKindText       = { link = "String" },
    CmpItemKindSnippet    = { fg = c.purple },
    CmpItemKindConstant   = { link = "Constant" },
    CmpItemKindField      = { fg = c.brblack },
    CmpItemKindProperty   = { fg = c.brblack },
    CmpItemKindModule     = { fg = c.cyan },

    -- blink.cmp
    BlinkCmpMenu              = { link = "NormalFloat" },
    BlinkCmpMenuBorder       = { link = "FloatBorder" },
    BlinkCmpMenuSelection    = { bg = c.lgrey1, bold = true },
    BlinkCmpLabel            = { fg = c.fg },
    BlinkCmpLabelMatch       = { fg = c.blue, bold = true },
    BlinkCmpLabelDeprecated  = { fg = c.grey, strikethrough = true },
    BlinkCmpLabelDetail      = { link = "Comment" },
    BlinkCmpLabelDescription = { link = "Comment" },
    BlinkCmpKind             = { fg = c.purple },
    BlinkCmpDoc              = { link = "NormalFloat" },
    BlinkCmpDocBorder        = { link = "FloatBorder" },
    BlinkCmpDocSeparator     = { link = "FloatBorder" },
    BlinkCmpGhostText        = { link = "Comment" },
    BlinkCmpSignatureHelp    = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },

    -- neo-tree.nvim
    NeoTreeNormal       = { link = "Normal" },
    NeoTreeNormalNC     = { link = "NormalNC" },
    NeoTreeDirectoryName= { fg = c.fg },
    NeoTreeDirectoryIcon= { fg = c.blue },
    NeoTreeRootName     = { fg = c.fg, bold = true },
    NeoTreeFileName     = { fg = c.fg },
    NeoTreeFileIcon     = { fg = c.grey },
    NeoTreeIndentMarker = { fg = c.lgrey2 },
    NeoTreeExpander     = { fg = c.grey },
    NeoTreeGitModified  = { fg = c.orange },
    NeoTreeGitAdded     = { fg = c.green },
    NeoTreeGitDeleted   = { fg = c.red },
    NeoTreeGitUntracked = { fg = c.grey },
    NeoTreeGitConflict  = { fg = c.red, bold = true },
    NeoTreeGitIgnored   = { fg = c.lgrey2 },
    NeoTreeDimText      = { link = "Comment" },
    NeoTreeMessage      = { link = "Comment" },
    NeoTreeTitleBar     = { fg = c.fg, bg = c.lgrey2, bold = true },

    -- nvim-tree
    NvimTreeNormal          = { link = "Normal" },
    NvimTreeNormalNC        = { link = "NormalNC" },
    NvimTreeFolderName      = { fg = c.fg },
    NvimTreeFolderIcon      = { fg = c.blue },
    NvimTreeOpenedFolderName= { fg = c.fg, bold = true },
    NvimTreeRootFolder      = { fg = c.fg, bold = true },
    NvimTreeIndentMarker    = { fg = c.lgrey2 },
    NvimTreeGitDirty        = { fg = c.orange },
    NvimTreeGitNew          = { fg = c.green },
    NvimTreeGitDeleted      = { fg = c.red },
    NvimTreeGitStaged       = { fg = c.green },
    NvimTreeSpecialFile     = { fg = c.purple, underline = true },
    NvimTreeImageFile       = { fg = c.fg },
    NvimTreeSymlink         = { fg = c.cyan },
    NvimTreeWindowPicker    = { link = "WhiteOnPurple" },

    -- oil.nvim
    OilDir        = { fg = c.blue, bold = true },
    OilDirIcon    = { fg = c.blue },
    OilLink       = { fg = c.cyan },
    OilLinkTarget = { link = "Comment" },
    OilCopy       = { fg = c.green, bold = true },
    OilMove       = { fg = c.orange, bold = true },
    OilChange     = { fg = c.orange, bold = true },
    OilCreate     = { fg = c.green, bold = true },
    OilDelete     = { fg = c.red, bold = true },
    OilRestore    = { fg = c.green, bold = true },

    -- bufferline.nvim
    BufferLineFill              = { bg = c.lgrey2 },
    BufferLineBackground        = { fg = c.grey, bg = c.lgrey2 },
    BufferLineBufferSelected    = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineBufferVisible     = { fg = c.grey, bg = c.lgrey1 },
    BufferLineIndicatorSelected = { fg = c.blue, bg = c.bg },
    BufferLineModified          = { fg = c.orange, bg = c.lgrey2 },
    BufferLineModifiedSelected  = { fg = c.orange, bg = c.bg },
    BufferLineModifiedVisible   = { fg = c.orange, bg = c.lgrey1 },
    BufferLineSeparator         = { fg = c.lgrey2, bg = c.lgrey2 },
    BufferLineSeparatorSelected = { fg = c.lgrey2, bg = c.bg },
    BufferLineCloseButton       = { fg = c.grey, bg = c.lgrey2 },
    BufferLineCloseButtonSelected = { fg = c.red, bg = c.bg },

    -- indent-blankline (v3) + legacy
    IblIndent     = { fg = c.lgrey2 },
    IblWhitespace = { fg = c.lgrey2 },
    IblScope      = { fg = c.lgrey3 },
    IndentBlanklineChar        = { fg = c.lgrey2 },
    IndentBlanklineContextChar = { fg = c.lgrey3 },

    -- which-key.nvim
    WhichKey          = { fg = c.blue },
    WhichKeyGroup     = { fg = c.fg, bold = true },
    WhichKeyDesc      = { fg = c.fg },
    WhichKeySeparator = { link = "Comment" },
    WhichKeyValue     = { link = "Comment" },
    WhichKeyFloat     = { link = "NormalFloat" },
    WhichKeyBorder    = { link = "FloatBorder" },
    WhichKeyTitle     = { fg = c.fg, bold = true },

    -- dashboard-nvim
    DashboardHeader       = { fg = c.blue },
    DashboardFooter       = { fg = c.grey },
    DashboardShortCut     = { fg = c.purple },
    DashboardDesc         = { fg = c.fg },
    DashboardKey          = { fg = c.red },
    DashboardIcon         = { fg = c.cyan },
    DashboardProjectTitle = { fg = c.fg, bold = true },
    DashboardFiles        = { fg = c.fg },

    -- alpha-nvim
    AlphaHeader   = { fg = c.blue },
    AlphaButtons  = { fg = c.fg },
    AlphaShortcut = { fg = c.purple },
    AlphaFooter   = { fg = c.grey },

    -- noice.nvim
    NoiceCmdline            = { link = "MsgArea" },
    NoiceCmdlineIcon        = { fg = c.blue },
    NoiceCmdlinePopup       = { link = "NormalFloat" },
    NoiceCmdlinePopupBorder = { link = "FloatBorder" },
    NoiceCmdlinePopupTitle  = { fg = c.fg, bold = true },
    NoiceConfirmBorder      = { link = "FloatBorder" },
    NoiceMini               = { link = "MsgArea" },
    NoiceVirtualText        = { link = "Comment" },
    NoicePopupBorder        = { link = "FloatBorder" },

    -- nvim-notify
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder  = { fg = c.orange },
    NotifyINFOBorder  = { fg = c.cyan },
    NotifyDEBUGBorder = { fg = c.grey },
    NotifyTRACEBorder = { fg = c.purple },
    NotifyERRORIcon   = { fg = c.red },
    NotifyWARNIcon    = { fg = c.orange },
    NotifyINFOIcon    = { fg = c.cyan },
    NotifyDEBUGIcon   = { fg = c.grey },
    NotifyTRACEIcon   = { fg = c.purple },
    NotifyERRORTitle  = { fg = c.red, bold = true },
    NotifyWARNTitle   = { fg = c.orange, bold = true },
    NotifyINFOTitle   = { fg = c.cyan, bold = true },
    NotifyDEBUGTitle  = { fg = c.grey, bold = true },
    NotifyTRACETitle  = { fg = c.purple, bold = true },
    NotifyERRORBody   = { link = "Normal" },
    NotifyWARNBody    = { link = "Normal" },
    NotifyINFOBody    = { link = "Normal" },
    NotifyDEBUGBody   = { link = "Normal" },
    NotifyTRACEBody   = { link = "Normal" },

    -- flash.nvim
    FlashBackdrop = { fg = c.grey },
    FlashMatch    = { link = "Search" },
    FlashCurrent  = { bg = c.lyellow },
    FlashLabel    = { link = "WhiteOnRed" },
    FlashPrompt   = { link = "MsgArea" },

    -- hop.nvim
    HopNextKey   = { link = "WhiteOnRed" },
    HopNextKey1  = { link = "WhiteOnRed" },
    HopNextKey2  = { link = "WhiteOnYellow" },
    HopUnmatched = { link = "Comment" },
    HopCursor    = { link = "Cursor" },

    -- leap.nvim
    LeapMatch          = { link = "WhiteOnRed" },
    LeapLabel          = { link = "WhiteOnRed" },
    LeapLabelPrimary   = { link = "WhiteOnRed" },
    LeapLabelSecondary = { link = "WhiteOnYellow" },
    LeapBackdrop       = { link = "Comment" },

    -- clever-f / sneak (kept from original)
    CleverFDefaultLabel = { link = "WhiteOnRed" },
    Sneak               = { link = "WhiteOnRed" },
    SneakScope          = { bg = c.lblue },

    -- todo-comments.nvim
    TodoBgTODO  = { fg = c.white, bg = c.cyan, bold = true },
    TodoFgTODO  = { fg = c.cyan },
    TodoSignTODO= { fg = c.cyan },
    TodoBgFIX   = { fg = c.white, bg = c.red, bold = true },
    TodoFgFIX   = { fg = c.red },
    TodoSignFIX = { fg = c.red },
    TodoBgHACK  = { fg = c.white, bg = c.orange, bold = true },
    TodoFgHACK  = { fg = c.orange },
    TodoSignHACK= { fg = c.orange },
    TodoBgWARN  = { fg = c.white, bg = c.orange, bold = true },
    TodoFgWARN  = { fg = c.orange },
    TodoSignWARN= { fg = c.orange },
    TodoBgPERF  = { fg = c.white, bg = c.purple, bold = true },
    TodoFgPERF  = { fg = c.purple },
    TodoSignPERF= { fg = c.purple },
    TodoBgNOTE  = { fg = c.white, bg = c.green, bold = true },
    TodoFgNOTE  = { fg = c.green },
    TodoSignNOTE= { fg = c.green },
    TodoBgTEST  = { fg = c.white, bg = c.cyan, bold = true },
    TodoFgTEST  = { fg = c.cyan },
    TodoSignTEST= { fg = c.cyan },

    -- trouble.nvim
    TroubleNormal     = { link = "NormalFloat" },
    TroubleNormalNC   = { link = "NormalFloat" },
    TroubleText       = { fg = c.fg },
    TroubleCount      = { fg = c.purple, bold = true },
    TroubleIndent     = { fg = c.lgrey2 },
    TroubleFoldIcon   = { fg = c.grey },
    TroublePos        = { link = "Comment" },
    TroubleSource     = { link = "Comment" },

    -- nvim-navic
    NavicText            = { fg = c.fg },
    NavicSeparator       = { fg = c.grey },
    NavicIconsFunction   = { link = "Function" },
    NavicIconsMethod     = { link = "Function" },
    NavicIconsClass      = { link = "Type" },
    NavicIconsStruct     = { link = "Type" },
    NavicIconsInterface  = { link = "Type" },
    NavicIconsEnum       = { link = "Type" },
    NavicIconsVariable   = { link = "Identifier" },
    NavicIconsConstant   = { link = "Constant" },
    NavicIconsProperty   = { fg = c.brblack },
    NavicIconsField      = { fg = c.brblack },
    NavicIconsKeyword    = { link = "Keyword" },
    NavicIconsString     = { link = "String" },
    NavicIconsNumber     = { link = "Number" },
    NavicIconsModule     = { fg = c.cyan },

    -- vim-illuminate
    IlluminatedWordText  = { bg = c.lgrey1 },
    IlluminatedWordRead  = { bg = c.lgrey1 },
    IlluminatedWordWrite = { bg = c.lgrey1, bold = true },

    -- mini.nvim
    MiniStatuslineModeNormal  = { fg = c.white, bg = c.blue, bold = true },
    MiniStatuslineModeInsert  = { fg = c.white, bg = c.green, bold = true },
    MiniStatuslineModeVisual  = { fg = c.white, bg = c.purple, bold = true },
    MiniStatuslineModeReplace = { fg = c.white, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.white, bg = c.orange, bold = true },
    MiniStatuslineModeOther   = { fg = c.white, bg = c.cyan, bold = true },
    MiniStatuslineDevinfo     = { fg = c.fg, bg = c.lgrey2 },
    MiniStatuslineFilename    = { fg = c.fg, bg = c.lgrey1 },
    MiniStatuslineFileinfo    = { fg = c.fg, bg = c.lgrey2 },
    MiniStatuslineInactive    = { link = "StatusLineNC" },
    MiniIndentscopeSymbol     = { fg = c.lgrey3 },
    MiniIndentscopePrefix     = { nocombine = true },
    MiniDiffSignAdd           = { fg = c.green },
    MiniDiffSignChange        = { fg = c.orange },
    MiniDiffSignDelete        = { fg = c.red },
    MiniCursorword            = { bg = c.lgrey1 },
    MiniCursorwordCurrent     = { bg = c.lgrey1 },
    MiniFilesTitle            = { fg = c.fg, bold = true },
    MiniFilesTitleFocused     = { fg = c.fg, bold = true },
    MiniFilesNormal           = { link = "NormalFloat" },
    MiniFilesBorder           = { link = "FloatBorder" },
    MiniPickNormal            = { link = "NormalFloat" },
    MiniPickBorder            = { link = "FloatBorder" },
    MiniPickMatchCurrent      = { bg = c.lgrey1 },
    MiniPickMatchRanges       = { fg = c.blue, bold = true },
    MiniPickPrompt            = { fg = c.fg, bold = true },

    -- rainbow-delimiters
    RainbowDelimiterRed    = { fg = c.red },
    RainbowDelimiterYellow = { fg = c.orange },
    RainbowDelimiterBlue   = { fg = c.blue },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterGreen  = { fg = c.green },
    RainbowDelimiterViolet = { fg = c.purple },
    RainbowDelimiterCyan   = { fg = c.cyan },

    -- nvim-dap / nvim-dap-ui
    DapBreakpoint          = { fg = c.red },
    DapBreakpointCondition = { fg = c.orange },
    DapLogPoint            = { fg = c.blue },
    DapStopped             = { fg = c.green },
    DapStoppedLine         = { bg = c.lcyan },
    DapBreakpointRejected  = { fg = c.grey },
    DapUIVariable          = { fg = c.fg },
    DapUIScope             = { fg = c.blue },
    DapUIType              = { fg = c.cyan },
    DapUIValue             = { fg = c.fg },
    DapUIModifiedValue     = { fg = c.orange, bold = true },
    DapUIDecoration        = { fg = c.blue },
    DapUIThread            = { fg = c.green },
    DapUIStoppedThread     = { fg = c.blue },
    DapUISource            = { fg = c.purple },
    DapUILineNumber        = { fg = c.blue },
    DapUIFloatBorder       = { link = "FloatBorder" },
    DapUIWatchesEmpty      = { fg = c.red },
    DapUIWatchesValue      = { fg = c.green },
    DapUIWatchesError      = { fg = c.red },
    DapUIBreakpointsPath   = { fg = c.blue },
    DapUIBreakpointsInfo   = { fg = c.green },
    DapUIBreakpointsCurrentLine = { fg = c.green, bold = true },
    DapUIError             = { fg = c.red },

    -- mason.nvim
    MasonHeader              = { fg = c.white, bg = c.blue, bold = true },
    MasonHeaderSecondary     = { fg = c.white, bg = c.cyan, bold = true },
    MasonHighlight           = { fg = c.blue },
    MasonHighlightBlock      = { fg = c.white, bg = c.blue },
    MasonHighlightBlockBold  = { fg = c.white, bg = c.blue, bold = true },
    MasonMuted               = { link = "Comment" },
    MasonMutedBlock          = { fg = c.fg, bg = c.lgrey2 },
    MasonError               = { fg = c.red },

    -- lazy.nvim
    LazyH1           = { fg = c.white, bg = c.blue, bold = true },
    LazyButton       = { fg = c.fg, bg = c.lgrey1 },
    LazyButtonActive = { fg = c.white, bg = c.blue, bold = true },
    LazySpecial      = { fg = c.blue },
    LazyProgressDone = { fg = c.green },
    LazyProgressTodo = { fg = c.lgrey2 },
    LazyComment      = { link = "Comment" },
    LazyNormal       = { link = "NormalFloat" },
    LazyDir          = { fg = c.blue },
    LazyUrl          = { fg = c.blue, underline = true },
    LazyProp         = { link = "Comment" },
    LazyReasonPlugin = { fg = c.purple },
    LazyReasonEvent  = { fg = c.cyan },
    LazyReasonKeys   = { fg = c.orange },

    -- Neogit (ported from envy.vim, extended)
    NeogitDiffAdd              = { fg = c.green },
    NeogitDiffDelete           = { fg = c.red },
    NeogitDiffAddHighlight     = { link = "DiffAdd" },
    NeogitDiffDeleteHighlight  = { link = "DiffDelete" },
    NeogitDiffContextHighlight = { bg = c.lgrey1 },
    NeogitHunkHeader           = { fg = c.grey, bg = c.lgrey1, bold = true },
    NeogitHunkHeaderHighlight  = { bg = c.lgrey2, bold = true },
    NeogitBranch               = { fg = c.purple, bold = true },
    NeogitRemote               = { fg = c.green, bold = true },
    NeogitNotificationInfo     = { fg = c.cyan },
    NeogitNotificationWarning  = { fg = c.orange },
    NeogitNotificationError    = { fg = c.red },

    -- diffview.nvim
    DiffviewNormal            = { link = "Normal" },
    DiffviewStatusAdded       = { fg = c.green },
    DiffviewStatusModified    = { fg = c.orange },
    DiffviewStatusDeleted     = { fg = c.red },
    DiffviewStatusRenamed     = { fg = c.blue },
    DiffviewFilePanelTitle    = { fg = c.fg, bold = true },
    DiffviewFilePanelCounter  = { fg = c.purple, bold = true },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewFolderName        = { fg = c.blue },
    DiffviewFolderSign        = { fg = c.blue },
    DiffviewDim1              = { link = "Comment" },

    -- vim-fugitive (ported from envy.vim)
    FugitiveblameTime = { fg = c.blue },
    FugitiveblameHash = { fg = c.purple },
    gitCommitOverflow = { link = "ErrorMsg" },
    gitCommitSummary  = { link = "String" },

    -- ALE (ported from envy.vim)
    ALEErrorSign        = { link = "ErrorSign" },
    ALEError            = { link = "ErrorHighlight" },
    ALEWarningSign      = { link = "WarningSign" },
    ALEWarning          = { link = "WarningHighlight" },
    ALEVirtualTextError = { link = "ErrorHighlight" },
    ALEVirtualTextWarning = { link = "WarningHighlight" },

    -- coc.nvim (ported from envy.vim)
    CocFloating         = { link = "FloatWindow" },
    CocErrorSign        = { link = "ErrorSign" },
    CocErrorHighlight   = { link = "ErrorHighlight" },
    CocErrorFloat       = { link = "ErrorFloatWindow" },
    CocWarningSign      = { link = "WarningSign" },
    CocWarningHighlight = { link = "WarningHighlight" },
    CocWarningFloat     = { link = "WarningFloatWindow" },
    CocHintSign         = { link = "HintSign" },
    CocHintHighlight    = { link = "HintHighlight" },
    CocHintFloat        = { link = "HintFloatWindow" },
    CocInfoSign         = { link = "HintSign" },
    CocInfoHighlight    = { link = "HintHighlight" },
    CocInfoFloat        = { link = "HintFloatWindow" },
    CocListMode         = { link = "StatusLine" },
    CocListPath         = { link = "StatusLine" },
  }
end

return M
